"""add network_node

Revision ID: 3d372f36071f
Revises: a4e17c92f88b
Create Date: 2026-09-10 22:16:31.335221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d372f36071f'
down_revision = 'a4e17c92f88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('olt_device_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('onu_mac', sa.String(length=20), nullable=True),
    sa.Column('last_dereg_reason', sa.String(length=20), nullable=True),
    sa.Column('last_dereg_reason_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['olt_device_id'], ['network_device.id'], name=op.f('fk_network_node_olt_device_id_network_device')),
    sa.ForeignKeyConstraint(['parent_node_id'], ['network_node.id'], name=op.f('fk_network_node_parent_node_id_network_node')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_network_node_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_node'))
    )
    with op.batch_alter_table('network_node', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_network_node_onu_mac'), ['onu_mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_network_node_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_node', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_network_node_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_network_node_onu_mac'))

    op.drop_table('network_node')
    # ### end Alembic commands ###
