"""add admin_mobile_number to cs_agent_settings

Revision ID: 7d71301113fd
Revises: 5e8a7b1c3d2e
Create Date: 2026-09-14 00:28:22.560090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d71301113fd'
down_revision = '5e8a7b1c3d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mikrotik_server', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mikrotik_server_tenant_id'))

    op.drop_table('mikrotik_server')
    with op.batch_alter_table('billing_payment_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_billing_payment_attempt_whish_external_id'), type_='unique')

    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_business_settings_reporting_currency_currency'), 'currency', ['reporting_currency'], ['code'])

    with op.batch_alter_table('cs_agent_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_mobile_number', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_cs_agent_settings_tenant_id'), type_='unique')

    with op.batch_alter_table('customer_payment_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_customer_payment_link_view_token'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_customer_payment_link_whish_external_id'), type_='unique')

    with op.batch_alter_table('customer_whish_payment_attempt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_customer_whish_payment_attempt_whish_external_id'), type_='unique')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_payment_currency_currency'), 'currency', ['currency'], ['code'])

    with op.batch_alter_table('reseller', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('reseller_payment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_subscription_plan_currency_currency'), 'currency', ['currency'], ['code'])

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('supplier_payment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_public_pay_slug'), ['public_pay_slug'], unique=True)

    with op.batch_alter_table('ticket_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    with op.batch_alter_table('whats_app_settings', schema=None) as batch_op:
        batch_op.alter_column('app_secret',
               existing_type=sa.VARCHAR(length=200),
               type_=crypto.EncryptedString(),
               existing_nullable=True)

    with op.batch_alter_table('whats_app_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_template_meta_template_id'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_template_tenant_id'))
        batch_op.create_index(batch_op.f('ix_whats_app_template_meta_template_id'), ['meta_template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whats_app_template_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whats_app_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whats_app_template_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_whats_app_template_meta_template_id'))
        batch_op.create_index(batch_op.f('ix_whatsapp_template_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_template_meta_template_id'), ['meta_template_id'], unique=False)

    with op.batch_alter_table('whats_app_settings', schema=None) as batch_op:
        batch_op.alter_column('app_secret',
               existing_type=crypto.EncryptedString(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)

    with op.batch_alter_table('ticket_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_public_pay_slug'))

    with op.batch_alter_table('supplier_payment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('supplier', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('subscription_plan', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_subscription_plan_currency_currency'), type_='foreignkey')

    with op.batch_alter_table('sector', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('reseller_payment', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('reseller', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_currency_currency'), type_='foreignkey')

    with op.batch_alter_table('customer_whish_payment_attempt', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_customer_whish_payment_attempt_whish_external_id'), ['whish_external_id'])

    with op.batch_alter_table('customer_payment_link', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_customer_payment_link_whish_external_id'), ['whish_external_id'])
        batch_op.create_unique_constraint(batch_op.f('uq_customer_payment_link_view_token'), ['view_token'])

    with op.batch_alter_table('cs_agent_settings', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_cs_agent_settings_tenant_id'), ['tenant_id'])
        batch_op.drop_column('admin_mobile_number')

    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_business_settings_reporting_currency_currency'), type_='foreignkey')

    with op.batch_alter_table('billing_payment_attempt', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_billing_payment_attempt_whish_external_id'), ['whish_external_id'])

    op.create_table('mikrotik_server',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('host', sa.VARCHAR(length=255), nullable=False),
    sa.Column('api_port', sa.INTEGER(), nullable=False),
    sa.Column('use_tls', sa.BOOLEAN(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('last_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('service_name', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_mikrotik_server_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mikrotik_server'))
    )
    with op.batch_alter_table('mikrotik_server', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mikrotik_server_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###
