"""add upgrade_request table

Revision ID: 9dd046c3dc10
Revises: d5b73c902f25
Create Date: 2026-07-19 02:43:59.778728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dd046c3dc10'
down_revision = 'd5b73c902f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upgrade_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('requested_plan', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_upgrade_request_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upgrade_request'))
    )
    with op.batch_alter_table('upgrade_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upgrade_request_tenant_id'), ['tenant_id'], unique=False)
    # NOTE: the app_secret VARCHAR->EncryptedString "type change" autogenerate reports
    # is cosmetic (EncryptedString stores as TEXT) and intentionally omitted.


def downgrade():
    with op.batch_alter_table('upgrade_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upgrade_request_tenant_id'))
    op.drop_table('upgrade_request')
