"""add network_write_audit

Revision ID: a4e17c92f88b
Revises: f2b6c9d4e703
Create Date: 2026-09-08 17:00:00.000000

Hand-written rather than autogenerated, for the reason 5f65a6fd6e8d already
records: this repo's local SQLite database cannot reach the real head at all
(origin's bd054e2e7cf9 calls op.create_unique_constraint outside batch mode,
which SQLite rejects), so autogenerate has nothing valid to diff against.

Purely additive -- one new table, no change to any existing one. Inspects
before creating because production's real schema disagrees with migration
history in both directions, and because the container runs
`flask db upgrade && exec gunicorn`: a migration that raises is not a warning,
it is a full outage.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4e17c92f88b'
down_revision = 'f2b6c9d4e703'
branch_labels = None
depends_on = None


def _has_table(name):
    return name in sa.inspect(op.get_bind()).get_table_names()


def _has_index(table, name):
    if not _has_table(table):
        return False
    return name in {i['name'] for i in sa.inspect(op.get_bind()).get_indexes(table)}


def upgrade():
    if not _has_table('network_write_audit'):
        op.create_table(
            'network_write_audit',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.Integer(), nullable=False),
            sa.Column('customer_id', sa.Integer(), nullable=True),
            sa.Column('network_device_id', sa.Integer(), nullable=True),
            sa.Column('pppoe_username', sa.String(length=100), nullable=False),
            sa.Column('action', sa.String(length=10), nullable=False),
            sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
            sa.Column('requested_by_username', sa.String(length=80), nullable=True),
            sa.Column('job_id', sa.Integer(), nullable=True),
            sa.Column('outcome', sa.String(length=10), nullable=False,
                      server_default='queued'),
            sa.Column('message', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
            sa.ForeignKeyConstraint(['network_device_id'], ['network_device.id'], ondelete='SET NULL'),
            sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ondelete='SET NULL'),
            sa.ForeignKeyConstraint(['job_id'], ['network_agent_job.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id'),
        )

    # Guarded independently of the table check above: a drifted database can
    # have the table (e.g. a partial earlier run, or hand-applied DDL)
    # without one or both indexes, and that combination must still get the
    # missing index here rather than silently skipping it because the table
    # already existed. See f2b6c9d4e703's identical reasoning for
    # ix_customer_network_device_id.
    if not _has_index('network_write_audit', 'ix_network_write_audit_tenant_id'):
        op.create_index('ix_network_write_audit_tenant_id', 'network_write_audit',
                        ['tenant_id'], unique=False)
    if not _has_index('network_write_audit', 'ix_network_write_audit_created_at'):
        op.create_index('ix_network_write_audit_created_at', 'network_write_audit',
                        ['created_at'], unique=False)


def downgrade():
    if _has_table('network_write_audit'):
        op.drop_table('network_write_audit')
