"""add customer cpe_mac_address and onu_last_seen_at

Revision ID: c3a71d5e04b8
Revises: b71fe5010a39
Create Date: 2026-09-06 12:00:00.000000

Hand-written rather than autogenerated, for the reason 5f65a6fd6e8d already
records: this repo's local SQLite database cannot reach the real head at all
(origin's bd054e2e7cf9 calls op.create_unique_constraint outside batch mode,
which SQLite rejects), so autogenerate has nothing valid to diff against.
The operations below are exactly what it would emit from Customer's two new
columns and its new UniqueConstraint.

Additive only: two nullable columns on an existing table. No data is read,
written or moved, so this is safe to run against production's populated
customer table.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a71d5e04b8'
down_revision = 'b71fe5010a39'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpe_mac_address', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('onu_last_seen_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customer_cpe_mac_address'),
                              ['cpe_mac_address'], unique=False)
        batch_op.create_unique_constraint('uq_customer_tenant_cpe_mac',
                                          ['tenant_id', 'cpe_mac_address'])


def downgrade():
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint('uq_customer_tenant_cpe_mac', type_='unique')
        batch_op.drop_index(batch_op.f('ix_customer_cpe_mac_address'))
        batch_op.drop_column('onu_last_seen_at')
        batch_op.drop_column('cpe_mac_address')
