"""add network_agent.connector_fingerprint

Revision ID: d9e2b7c4a815
Revises: c3a71d5e04b8
Create Date: 2026-09-07 00:40:00.000000

Hand-written rather than autogenerated, for the reason 5f65a6fd6e8d already
records: this repo's local SQLite database cannot reach the real head at all
(origin's bd054e2e7cf9 calls op.create_unique_constraint outside batch mode,
which SQLite rejects), so autogenerate has nothing valid to diff against. The
operation below is exactly what it would emit from NetworkAgent's new column.

Additive only: one nullable column on a table holding one row per tenant. No
data is read, written or moved, and on Postgres 11+ adding a nullable column
with no default is a metadata-only change, so this does not rewrite the table.

The column is left NULL for every existing agent, which is the correct initial
state and not a gap to backfill: NULL means "this agent has not reported which
connector files it loaded", and _connector_status renders that as 'unknown'
rather than 'stale'. An agent already in the field genuinely has not reported,
and will not until it is restarted on a build that does.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e2b7c4a815'
down_revision = 'c3a71d5e04b8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('network_agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connector_fingerprint',
                                      sa.String(length=200), nullable=True))


def downgrade():
    with op.batch_alter_table('network_agent', schema=None) as batch_op:
        batch_op.drop_column('connector_fingerprint')
