"""consolidate mikrotik_server into network_device

Revision ID: f2b6c9d4e703
Revises: d9e2b7c4a815
Create Date: 2026-09-07 12:30:00.000000

Hand-written rather than autogenerated, for the reason 5f65a6fd6e8d already
records: this repo's local SQLite database cannot reach the real head at all
(origin's bd054e2e7cf9 calls op.create_unique_constraint outside batch mode,
which SQLite rejects), so autogenerate has nothing valid to diff against.

Every step inspects before acting. Production's real schema disagrees with
migration history in both directions, so "the column must already be there" is
not a safe assumption in either direction.

The mikrotik_server table is EMPTY in production -- the owner confirmed via
super-admin that no tenant has configured one and no customer is linked. The
copy-forward branch below exists anyway because the container runs
`flask db upgrade && exec gunicorn`: a migration that raises does not misbehave,
it takes the whole application down. Copying rows forward and keeping the
original table is the only outcome that neither fails the deploy nor destroys
data.

downgrade() recreates the table and the old column but does NOT restore rows
into mikrotik_server. That is lossless for the zero-row case, which is the case
that exists.

No logger.exception or exc_info=True anywhere here: the copied rows carry
encrypted device passwords, and Sentry's LoggingIntegration captures frame
locals at ERROR.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b6c9d4e703'
down_revision = 'd9e2b7c4a815'
branch_labels = None
depends_on = None


def _has_table(name):
    return name in sa.inspect(op.get_bind()).get_table_names()


def _has_column(table, column):
    if not _has_table(table):
        return False
    return column in {c['name'] for c in sa.inspect(op.get_bind()).get_columns(table)}


def _has_index(table, name):
    if not _has_table(table):
        return False
    return name in {i['name'] for i in sa.inspect(op.get_bind()).get_indexes(table)}


def upgrade():
    bind = op.get_bind()

    if not _has_column('network_device', 'service_name'):
        with op.batch_alter_table('network_device', schema=None) as batch_op:
            batch_op.add_column(sa.Column('service_name', sa.String(length=100),
                                          nullable=True))

    if not _has_column('customer', 'network_device_id'):
        with op.batch_alter_table('customer', schema=None) as batch_op:
            batch_op.add_column(sa.Column('network_device_id', sa.Integer(),
                                          nullable=True))
            batch_op.create_foreign_key('fk_customer_network_device_id',
                                        'network_device', ['network_device_id'], ['id'])

    # Column-granular above is not enough on its own: a drifted database can
    # have the column (e.g. a previous partial run, or hand-applied DDL)
    # without the index, and that combination must still get the index here
    # rather than silently skipping it because the column guard was false.
    if not _has_index('customer', 'ix_customer_network_device_id'):
        with op.batch_alter_table('customer', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_customer_network_device_id'),
                                  ['network_device_id'], unique=False)

    kept_old_table = False
    if _has_table('mikrotik_server'):
        rows = bind.execute(sa.text('SELECT COUNT(*) FROM mikrotik_server')).scalar() or 0
        if rows:
            # INSERT ... RETURNING cannot report the SOURCE row's id, so a
            # temporary column carries the correlation from old row to new.
            with op.batch_alter_table('network_device', schema=None) as batch_op:
                batch_op.add_column(sa.Column('migrated_from_mikrotik_server_id',
                                              sa.Integer(), nullable=True))
            # device_type and interface_labels are nullable=False with
            # Python-side defaults, which a raw INSERT does not get.
            bind.execute(sa.text("""
                INSERT INTO network_device
                    (tenant_id, name, host, api_port, use_tls, username, password,
                     status, last_checked_at, last_status, service_name,
                     device_type, interface_labels,
                     migrated_from_mikrotik_server_id)
                SELECT tenant_id, name, host, api_port, use_tls, username, password,
                       status, last_checked_at, last_status, service_name,
                       'mikrotik_ccr', '{}', id
                FROM mikrotik_server
            """))
            if _has_column('customer', 'mikrotik_server_id'):
                # A correlated subquery rather than UPDATE ... FROM: this has to
                # run on SQLite in the migration test as well as on Postgres.
                bind.execute(sa.text("""
                    UPDATE customer SET network_device_id = (
                        SELECT nd.id FROM network_device nd
                        WHERE nd.migrated_from_mikrotik_server_id
                              = customer.mikrotik_server_id
                    )
                    WHERE customer.mikrotik_server_id IS NOT NULL
                """))
            with op.batch_alter_table('network_device', schema=None) as batch_op:
                batch_op.drop_column('migrated_from_mikrotik_server_id')
            kept_old_table = True
            print('mikrotik_server had {} row(s): copied into network_device and '
                  'KEPT the original table as a backup. Drop it by hand once you '
                  'have checked the migrated rows.'.format(rows))

    # Before the table drop: this removes the FK that would otherwise block it.
    if _has_column('customer', 'mikrotik_server_id'):
        with op.batch_alter_table('customer', schema=None) as batch_op:
            batch_op.drop_column('mikrotik_server_id')

    if _has_table('mikrotik_server') and not kept_old_table:
        op.drop_table('mikrotik_server')


def downgrade():
    if not _has_table('mikrotik_server'):
        op.create_table(
            'mikrotik_server',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('tenant_id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('host', sa.String(length=255), nullable=False),
            sa.Column('api_port', sa.Integer(), nullable=False),
            sa.Column('use_tls', sa.Boolean(), nullable=False),
            sa.Column('username', sa.String(length=100), nullable=False),
            sa.Column('password', sa.Text(), nullable=False),
            sa.Column('service_name', sa.String(length=100), nullable=True),
            sa.Column('status', sa.String(length=20), nullable=True),
            sa.Column('last_checked_at', sa.DateTime(), nullable=True),
            sa.Column('last_status', sa.String(length=20), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id']),
            sa.PrimaryKeyConstraint('id'),
        )
        op.create_index('ix_mikrotik_server_tenant_id', 'mikrotik_server',
                        ['tenant_id'], unique=False)

    if not _has_column('customer', 'mikrotik_server_id'):
        with op.batch_alter_table('customer', schema=None) as batch_op:
            batch_op.add_column(sa.Column('mikrotik_server_id', sa.Integer(),
                                          nullable=True))
            batch_op.create_foreign_key('fk_customer_mikrotik_server_id',
                                        'mikrotik_server', ['mikrotik_server_id'], ['id'])

    if _has_column('customer', 'network_device_id'):
        with op.batch_alter_table('customer', schema=None) as batch_op:
            # Guarded independently of the column: on a drifted database the
            # column can survive without the index ever having existed, and
            # an unconditional drop_index raises on Postgres in that case.
            if _has_index('customer', 'ix_customer_network_device_id'):
                batch_op.drop_index(batch_op.f('ix_customer_network_device_id'))
            batch_op.drop_column('network_device_id')

    if _has_column('network_device', 'service_name'):
        with op.batch_alter_table('network_device', schema=None) as batch_op:
            batch_op.drop_column('service_name')
